FROM maven:eclipse-temurin as build
RUN mkdir /app
WORKDIR /app
COPY pom.xml .
RUN mvn -f pom.xml dependency:go-offline

COPY src/ /app/src/
RUN mvn clean package \
    -DskipTests -Dmaven.source.skip=true -Dmaven.javadoc.skip=true

FROM eclipse-temurin:21
RUN mkdir /app && chmod ugo+rwx /app
COPY --from=build /app/target/ecmr-backend-*.jar /app/ecmr-backend.jar
EXPOSE 8080
WORKDIR /app
# Using the cgroup memory limit for heap size is essential in running java applications in container environments
# This sets -XX:MaxRAM to whatever is configured for the container and sets -XX:MaxHeapSize to 1/4 of that
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/ecmr-backend.jar"]
