[[section-design-decisions]]
== Design Decisions

This section explains fundamental design decisions.
Stakeholders of an XXX must be able to comprehend and retrace important architecture decisions and their rationales.
Different solutions for a problem can be discussed, and why one approach was favored based on given criteria.
An ADR (architecture decision record) is created for every important decision.
Also, the list of selected third-party software used and their licences is displayed here.

=== Loose Coupling of Components

All components of XXX follow the Micro Services architecture and are executed in application containers.
There is no direct communication between individual components.
This is also called loose coupling.
Each component communicates within the XXX on an event-driven basis using the AMQP protocol.

=== Scaling of Components

In Silicon Economy, Micro Services are running in containers and are managed by a Kubernetes cluster.
This enables the XXX to scale individual components.
Scaling is used to respond to component workloads: If a component is heavily utilized, another instance is started and stopped again after the utilization has decreased.
The basis for it is the evaluation of the resources use of a component.
For this purpose, the CPU and RAM utilization as well as the number of packets sent/received to/from the network interface of a component are evaluated to control scaling.
The adapters also scale according to the number of ... using the primary replica concept.

==== Options for Scaling

In addition to the (semi-) automatic scaling concepts described below it is currently possible to scale each adapter instance freely by manual operation with any of the K8s interfaces (CLI, K8s-Webfrontend, etc).

===== Decentralized Solution

[cols="2",options="header"]
|===
|Advantage
|Disadvantage 2

|Decentralized, Relatively fail-safe, Much code reusable
|Each ... instance needs access to database, Distribution logic has to be written (and tested) by developers

|Column 1, row 2
|Column 2, row 2

|Column 1, row 3
|Column 2, row 3

|Column 1, row 4
|Column 2, row 4
|===

===== Central Solution

[cols="2",options="header"]
|===
|Advantage
|Disadvantage 2

|Uses capabilities of RabbitMQ.
Distribution logic facilitates actual resource consumption, Fewer accesses to CouchDB
| Removal of ... is more complex

|Column 1, row 2
|Column 2, row 2

|Column 1, row 4
|Column 2, row 4
|===

===== Solution used

short description and main reason.

=== Third Party Software Libraries

The following third party software libraries are used for the XXX.
This list displays their names, versions and their concrete Open Source license being compatible with the Open Source license to be used for Silicon Economy projects.
The list was generated by using: WIP, will be provided on a per-component basis in the near future.

Add here Link to GitLab generated table/file(s).
Here may be multiple entries.

=== Use of Generated Code

The use of Lombok reduces amount of code to write, understand and test.
Lombok generated code is excluded from test coverage requirements.

A popular data format for XXX and embedded devices is Protobuf.
In the XXX, device-specific Protobuf converter implementations are generated by a Protobuf compiler and the resulting code is excluded from test coverage requirements.

=== Ingress Routes (HTTP, WS)

Since there is only a single instance of an XXX per cluster, externally reachable services can get by with a fixed suffix (identical to the namespace for simplicity) in the URL.
This is necessary to provide uniqueness for function names that are not very specific.
To clearly distinguish between routing to a service and routing within a service, the host part of the domain section of the URL is used for routing to a service whenever possible.
The following scheme applies:

    xxx-<function>.[prefix.cluster.domain.org]

No '.' may be added to this.
The first '.' of the URL is the one before "prefix".
This restriction results from the wildcard TLS certificate issued by the Fraunhofer Gesellschaft, as well as the DNS.
Instead, as many '-'s can and may be used as desired.
It should be noted that '_' in domain names and thus in the ingress URLs are invalid according to https://tools.ietf.org/html/rfc952[ietfs.org] and the above scheme.

This adheres to general guidelines for Silicon Economy URL naming.

Examples:

https://xxx-management.apps.sele.iml.fraunhofer.de/

=== Other Ingress

Since often power consumption, which directly correlates with transmission duration, is a critical factor when designing XXX, not all incoming traffic can be feasibly transmitted over HTTP or WS connections.
Therefore, means of network communication other than HTTP/WS (which are routable on application layer protocol level) must be possible.
This can be achieved by falling back to TCP traffic on dedicated ports for incoming data.

Currently, the ... service of the XXX is accessible over TCP/5683 to achieve communication with ....
